### ISSUE TITLE
How to upgrade from 2.3.2 to 3.0.0?

### ISSUE THREAD

**Issue by j0k3r** [stldo/url-slug#15]
Looks like the upgrade needs work.

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/travis/build/project/node_modules/url-slug/dist/index.js
require() of ES modules is not supported.
```

We are using it like:

```javascript
import urlSlug from 'url-slug'

//...

const slug = urlSlug(title)
```

How can we properly upgrade?
Also, what are changes in 3.0.0? 

Maybe you should create a CHANGELOG file or use GitHub release to add more information about your tag.

**Comment by darcdev** [comment]
I have the same error , I'm trying to use with gatsby to generate dynamic pages , and I import it and it throws me the same  @j0k3r 
error

**Comment by stldo** [comment]
Hi! Thanks, @darcdev, for pointing a helpful way to reproduce the bug. I'm working on a fix and will release it soon. @j0k3r, the main change on this update is removing the `unidecode` dependency, which greatly reduced the library size, and removing some options that were marked as deprecated. I'm very, very busy lately, but maintaining a CHANGELOG is on the plans.

**Comment by stldo** [comment]
I've published a new version on npm (`3.0.1`) that should correct this error. Please let me know if everything is working fine, so I can close this issue. I'm sorry for any inconvenience, thanks for reporting it.

**Comment by darcdev** [comment]
Hello friend again, I tried the code with the new version of the package and it worked very well when importing it, which it did not do before the update, thanks for fixing it, good luck friend :100:

**Comment by j0k3r** [comment]
Problem fixed too, thanks for the fast fix @stldo 👏
