### ISSUE TITLE
v3.0.0 does not work with Node.js version 14.15 (LTS) as ESM

### ISSUE THREAD

**Issue by primeare** [stldo/url-slug#16]
### Problem statement
When the `url-slug` library version 3.0.0 is imported in Node.js version 14.15.4 as ECMAScript Module (ESM), the library can only be used from the `global` scope. Neither default import nor named import, nor entire module contents import is working.

```js
// NOT WORKING CODE:

// default import
import urlSlug from 'url-slug';
urlSlug('...');

// named import
import { urlSlug } from 'url-slug';
urlSlug('...');

// entire module contents import
import * as urlSlug from 'url-slug';
urlSlug('...');

// WORKING CODE:

import 'url-slug';
global.urlSlug('...');
```

### Issue reproducing environment
- Node.js version 14.15.4
- macOS Bis Sur (11.1)
- project's `package.json` is configured as ESM-ready: `"type": "module"`

**Comment by stldo** [comment]
Hi, thanks for your report. Try updating to 3.0.1, it should fix this issue. Please let me know if it works, so I can close this issue.

**Comment by primeare** [comment]
I have updated to version 3.0.1, and the default import is working correctly. The issue can be closed.
