### ISSUE TITLE
urlSlug produces extra fragments for strings containing camelcase

### ISSUE THREAD

**Issue by joeptacek** [stldo/url-slug#7]
I'm using url-slug@2.1.1 and was surprised by this behavior — it it intentional?
```javascript
const slug = urlSlug('Brand new iMac');
// expected: brand-new-imac
// actual: brand-new-i-mac
```

**Comment by stldo** [comment]
Yes, splitting camel cases is the intended behavior. Would an option to enable/disable this be useful?

**Comment by joeptacek** [comment]
Yes, this option would be useful for me — I'm hoping to match the default behavior of Jekyll's [slugify filter](https://github.com/jekyll/jekyll/blob/0f4b7be88ddd39593c226486f056f7402e75299c/lib/jekyll/utils.rb) as closely as possible.

**Comment by stldo** [comment]
Ok, this option could be helpful on use cases which require compatibility with other slug implementations. It'll be added on the next minor version.

**Comment by joeptacek** [comment]
Thank you!

**Comment by stldo** [comment]
@joeptacek I've published an alpha version where you can find an option for disabling camel case. It's not documented yet, but it can be set through an options object — `urlSlug.convert('camelCase', { camelCase: false })` should return `'camelcase'`. The `separator` and `transformer` options can be set through this object too. I hope it helps you!
