### ISSUE TITLE
bug with special char

### ISSUE THREAD

**Issue by leponot** [stldo/url-slug#8]
replace quote in the file please

we have an invalid character with `

**Comment by stldo** [comment]
Could you be more clear, please? Are you referring to template literals? If so, this module requires at least Node v4.

**Comment by leponot** [comment]
const CONVERT_CAMELCASE = new RegExp(`[A-Za-z0-9]*?${BASE}|[A-Za-z0-9]+`, 'g')

i have a trouble with this ` when i use with webpack after version 2.0.0
if i replace with ' or " it's ok

**Comment by stldo** [comment]
Browser support is planned for the next major version. url-slug is currently only tested on Node.js, but you can try using `babel-preset-env` to convert the ES6 syntax and try it on the browser. For now, this issue will be closed.
